# Generated by Django 3.0.7 on 2020-06-22 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog_Photo',
        ),
        migrations.DeleteModel(
            name='Blog_video',
        ),
        migrations.DeleteModel(
            name='Cinematography',
        ),
        migrations.DeleteModel(
            name='Contact_Us',
        ),
        migrations.DeleteModel(
            name='Hire_Us',
        ),
        migrations.DeleteModel(
            name='Photography',
        ),
        migrations.DeleteModel(
            name='PhotoOnHomePage',
        ),
        migrations.DeleteModel(
            name='VideoOnHomePage',
        ),
    ]
