# Generated by Django 3.0 on 2020-06-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_blog_photo_blog_video_cinematography_contact_us_hire_us_photography_photoonhomepage_videoonhomepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_photo',
            name='image',
            field=models.ImageField(upload_to='media/image'),
        ),
        migrations.AlterField(
            model_name='blog_video',
            name='clip',
            field=models.FileField(upload_to='media/video'),
        ),
        migrations.AlterField(
            model_name='cinematography',
            name='clip',
            field=models.FileField(upload_to='media/video'),
        ),
        migrations.AlterField(
            model_name='photography',
            name='image',
            field=models.ImageField(upload_to='media/image'),
        ),
        migrations.AlterField(
            model_name='photoonhomepage',
            name='image',
            field=models.ImageField(upload_to='media/image'),
        ),
        migrations.AlterField(
            model_name='videoonhomepage',
            name='clip',
            field=models.FileField(upload_to='media/video'),
        ),
    ]
