# Generated by Django 3.0 on 2020-06-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studio', '0005_auto_20200627_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/image')),
                ('Bride_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Groom_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Blog Photo Table',
            },
        ),
        migrations.CreateModel(
            name='Blog_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip', models.FileField(upload_to='media/video')),
                ('Bride_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Groom_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Blog Video Table',
            },
        ),
        migrations.CreateModel(
            name='Cinematography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip', models.FileField(upload_to='media/video')),
            ],
            options={
                'verbose_name': 'Cinematography Table',
            },
        ),
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('msg', models.CharField(max_length=600)),
            ],
            options={
                'verbose_name': 'Client Inquiry Table',
            },
        ),
        migrations.CreateModel(
            name='Hire_Us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason1', models.CharField(blank=True, max_length=100, null=True)),
                ('reason2', models.CharField(blank=True, max_length=100, null=True)),
                ('reason3', models.CharField(blank=True, max_length=100, null=True)),
                ('reason4', models.CharField(blank=True, max_length=100, null=True)),
                ('reason5', models.CharField(blank=True, max_length=100, null=True)),
                ('reason6', models.CharField(blank=True, max_length=100, null=True)),
                ('reason7', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Reason To Hire Us Table',
            },
        ),
        migrations.CreateModel(
            name='Photography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/image')),
            ],
            options={
                'verbose_name': 'Photography Table',
            },
        ),
        migrations.CreateModel(
            name='PhotoOnHomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/image')),
            ],
            options={
                'verbose_name': 'Home Page Photo Table',
            },
        ),
        migrations.CreateModel(
            name='VideoOnHomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip', models.FileField(upload_to='media/video')),
            ],
        ),
    ]
